package org.albaslug.drawme.service;

import org.springframework.stereotype.Service;

import java.util.Random;

@Service
public class ActionService {

    private Random random = new Random();

    public String getAction() {
        return actions[random.nextInt(actions.length)];
    }

    private static String[] actions = {
            "Ride",
            "Sit down",
            "Stand up",
            "Fight",
            "Laugh",
            "Read",
            "Play",
            "Listen",
            "Cry",
            "Think",
            "Sing",
            "Watch TV",
            "Dance",
            "Turn on",
            "Turn off",
            "Win",
            "Fly",
            "Cut",
            "Throw away",
            "Sleep",
            "Close",
            "Open",
            "Write",
            "Give",
            "Jump",
            "Eat",
            "Drink",
            "Cook",
            "Wash",
            "Wait",
            "Climb",
            "Talk",
            "Crawl",
            "Dream",
            "Dig",
            "Clap",
            "Knit",
            "Sew",
            "Smell",
            "Kiss",
            "Hug",
            "Snore",
            "Bathe",
            "Bow",
            "Paint",
            "Dive",
            "Ski",
            "Stack",
            "Buy",
            "Shake",
            "Bend",
            "Lift",
            "Carry",
            "Kneel",
            "Hold",
            "Sit",
            "Drag",
            "Jump",
            "Leap",
            "Pick up",
            "Punch",
            "Pull",
            "Dive",
            "Push",
            "Run",
            "Lean",
            "Squat",
            "Throw",
            "Tiptoe",
            "Walk",
            "Hit",
            "Catch",
            "Kick",
            "Kiss",
            "Clap",
            "Laugh",
            "Dance",
            "Break",
            "Stand",
            "Jog",
            "March",
            "Wave",
            "Talk",
            "Open",
            "Cartwheel",
            "Put down",
            "Stretch",
            "Drop",
            "Point",
            "Slip",
            "Trip",
            "Look",
            "Cry",
            "Lie down",
            "Pour",
            "Crawl",
            "Do the laundry",
            "Hang the clothes",
            "Iron the clothes",
            "Make the bed",
            "Go to bed",
            "Wake up",
            "Brush the teeth",
            "Drive to work",
            "Get home",
            "Take a bath",
            "Brush your hair",
            "Surf the net",
            "Play with friends",
            "Go to school",
            "Go shopping",
            "Exercise",
            "Wash the car",
            "Get dressed",
            "Go out with a friend",
            "Take pictures",
            "Play the guitar",
            "Water the plant",
            "Go for a walk",
            "Work",
            "Have breakfast",
            "Have lunch",
            "Have dinner",
            "Make dinner",
            "Fold the laundry",
            "Surf the net",
            "Feed the dog",
            "Take a taxi",
            "Wait for the bus",
            "Paint the picture",
            "Have a break (U.K) – Take a break (U.S)",
            "Walk the dog",
            "Take out the rubbish (U.S)",
            "Sweep the floor",
            "Rake the leaves",
            "Read the news",
            "Clean the window",
            "Cut the grass",
            "Do the dishes",
            "Paint the house",
            "Teach",
            "Think",
            "Spell",
            "Give",
            "Study",
            "Read",
            "Cut",
            "Experiment",
            "Observe",
            "Listen",
            "Play",
            "Sing",
            "Say",
            "Draw",
            "Count",
            "Calculate",
            "Open",
            "Close",
            "Paint",
            "Show",
            "Explain",
            "Ask",
    };

}
